metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/snapshots"

replication_factor = 1
consistency_mode = "consistent"

metadata_fsync = true
data_fsync = false
metadata_auto_snapshot_interval = "6h"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "storage:3901"
rpc_secret = "80790989da650809459164eee419fde234dd87b32200d8af0cdcea8916b6dfa3"

[s3_api]
api_bind_addr = "0.0.0.0:3900"
s3_region = "us-east-1"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = ".web.garage"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "K52O6zSXo8A6KvQVQR2VttRSGmV0uAtTgdKuzvKlhlA="
metrics_token = "K52O6zSXo8A6KvQVQR2VttRSGmV0uAtTgdKuzvKlhlA="