name: JS

on:
  push:
    paths:
      - mlflow/server/js/**
      - .github/workflows/js.yml
    branches:
      - master
      - branch-[0-9]+.[0-9]+
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - mlflow/server/js/**
      - .github/workflows/js.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        option: [--testPathPattern, --testPathIgnorePatterns]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: mlflow/server/js
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Disable problem matcher
        if: runner.os == 'Windows'
        run: |
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
      - name: Install dependencies (windows)
        if: runner.os == 'Windows'
        run: |
          # On Windows, `yarn install` changes hash of @databricks/design-system in yarn.lock.
          # Use `--no-immutable` to allow the change.
          yarn install --no-immutable
          git diff
      - name: Install dependencies (non-windows)
        if: runner.os != 'Windows'
        run: |
          yarn install --immutable
      - name: Run lint
        run: |
          yarn lint
      - name: Run prettier
        run: |
          yarn prettier:check
      - name: Run extract-i18n lint
        run: |
          yarn i18n:check
      - name: Run tests
        run: |
          yarn test --silent ${{ matrix.option }} src/experiment-tracking/components
      - name: Run build
        if: runner.os == 'Linux'
        env:
          # Prevent warnings (emitted from react-pdf) from being treated as errors
          # https://github.com/wojtekmaj/react-pdf/issues/280
          CI: false
        run: |
          yarn build
