# Triggers rerun-workflow-run.yml on PR approval.
# See https://stackoverflow.com/questions/67247752/how-to-use-secret-in-pull-request-review-similar-to-pull-request-target for why we need this approach and how it works.
name: rerun

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.review.state == 'approved'
    steps:
      - name: Upload PR number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir -p /tmp/pr
          echo $PR_NUMBER > /tmp/pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: /tmp/pr/
