# Triggered by rerun.yml on PR approval.
name: rerun-workflow-run
on:
  workflow_run:
    workflows: [rerun]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  rerun:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      actions: write # to rerun github action workflows
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
      - name: Download PR number
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const rerun = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/rerun.js`);
            await rerun.download({ context, github });

      - name: Unzip PR number
        run: unzip pr_number.zip

      - name: Rerun workflows
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const rerun = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/rerun.js`);
            await rerun.rerun({ context, github });
