name: sklearn

# A cron job to ensure autologging works properly in older versions of scikit-learn

on:
  schedule:
    # Run this action daily at 7:00 UTC
    - cron: "0 7 * * *"
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/sklearn.yml
      - mlflow/sklearn/**

jobs:
  sklearn:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          # include this unsupported version to ensure autologging emits a warning properly.
          - "0.20.2"
          # unsupported versions
          # --------------------
          # supported versions
          - "0.20.3"
          - "0.21.2"
          - "0.22.2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r dev/small-requirements.txt
      - name: Update scikit-learn
        run: |
          pip install scikit-learn==${{ matrix.version }}
      - name: Run tests
        run: |
          pytest --verbose --large tests/sklearn/test_sklearn_autolog.py
      - name: Run examples
        working-directory: examples/sklearn_autolog
        run: |
          set -x
          python simple.py
          python pipeline.py
